version: '2'

services:
  db:
    image: mysql:5.7
    volumes:
      - ~/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    networks:
      - back

  wordpress:
    #deploy:
    # replicas: 5
    # resources:
    #  limits:
    #   cpus: "0.1"
    #   memory: 50M
    # restart_policy:
    #  condition: on-failure
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 80:80
      - 443:443
      - 21:21
    restart: always
    volumes:
      - ~/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      MYSQL_ROOT_PASSWORD: dbrootpass
      WORDPRESS_DB_USER: dbuser
      WORDPRESS_DB_PASSWORD: dbpass
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: dbrootpass
    networks:
      - back

volumes:
  db_data:
  wp-content:
networks:
  back:
