version: '3.3'

services:
  db:
    image: mysql
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - back

  wordpress:
    #deploy:
    #  replicas: 5
    #  resources:
    #    limits:
    #      cpus: "0.1"
    #      memory: 50M
    #  restart_policy:
    #    condition: on-failure
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - back

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpasswd
    networks:
      - back

volumes:
  db_data:
  wp-content:
networks:
  back:
